# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: New York Public Library Digital Preservation
email: nickkrabbenhoeft@nypl.org
description: >
  Blog for the Digital Preservation program at the New York Public Library.
baseurl: "/digpres" # the subpath of your site, e.g. /blog
permalink: /:year/:month/:day/:title.html
url: "http://nypl.github.io" # the base hostname & protocol for your site

twitter_username: "nypl_digpres"

# Build settings

theme: jekyll-theme-dinky