# Welcome to Jekyll!

# Site settings
title: NYPL Digital Preservation
email: digpres@nypl.org
description: >
  Documentation for the Digital Preservation program at the New York Public Library.
url: "https://nypl.github.io"
baseurl: "/digpres" # the subpath of your site, e.g. /blog

twitter_username: "nypl_digpres"

# Build settings

remote_theme: just-the-docs/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true

permalink: /posts/:title

ga_tracking: 2596733842
ga_tracking_anonymize_ip: true
